# Generated by Django 4.2.13 on 2025-02-28 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='contact_number',
            field=models.TextField(default='000000000000', max_length=12),
        ),
    ]
