# Generated by Django 4.2.13 on 2025-02-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='contact_number',
            field=models.TextField(blank=True, max_length=12, null=True),
        ),
    ]
