# Generated by Django 4.2.13 on 2025-02-28 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_author_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='contact_number',
            field=models.CharField(default='000000000000', max_length=12, validators=[django.core.validators.RegexValidator('^\\d+$', message='Only numbers are allowed.')]),
        ),
    ]
