# Generated by Django 4.2.13 on 2025-02-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_author_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.TextField(max_length=30, unique=True),
        ),
    ]
